M48
; DRILL file {KiCad (6.0.11)} date Thu Apr 25 23:10:31 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-25T23:10:31+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X88.6Y-75.11
X88.6Y-80.89
T2
X106.5Y-71.5
X106.5Y-98.5
X159.5Y-71.5
X159.5Y-98.5
T3
X87.0Y-68.0
X87.0Y-130.0
X179.0Y-68.0
X179.0Y-130.0
T0
M30
